name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
      - asuiah/*
  pull_request:

permissions:
  contents: write

concurrency:
  group: website-deployment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code repo
          uses: actions/checkout@v4
        - uses: pnpm/action-setup@v4
          with:
            version: 7
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 18.x
            cache: pnpm
        - name: Install dependencies
          with:
            working-directory: ./website
          run:  pnpm install
        - name: Build website
          run: pnpm build
          with:
            working-directory: ./website

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            working-directory: ./website
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # 构建生成的文件目录